# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 13:54
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lnglat',
            field=models.CharField(blank=True, max_length=50, validators=[blog.models.lnglat_validator]),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(choices=[('제목1', '제목1 레이블'), ('제목2', '제목2 레이블'), ('제목3', '제목3 레이블')], max_length=100),
        ),
    ]
