# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-23 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170920_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='authon',
            field=models.CharField(default='test', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
