# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-24 05:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='authon',
            new_name='author',
        ),
    ]
