# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-24 06:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170924_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='names',
        ),
    ]
