"""
Django settings for askdjango project.

Generated by 'django-admin startproject' using Django 1.11.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '#r@5p8b%5u&9-_y@bftlhc$qlube33qe!1bkx55l$94u*vumyn'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


# 이걸로 도메인 지정할 수 있음
# 이렇게 별로 두면 다 접속 하게 할 수 있음
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'debug_toolbar', #디버그툴바
    'blog',
    'dojo',
    'accounts',

]

MIDDLEWARE = [
    'debug_toolbar.middleware.DebugToolbarMiddleware', #디버그툴바
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'askdjango.urls'



#Django Template Loader
#여러가지가 있지만 가장 중요한건 app_directories.Loader 과 filesystem.Loader 존재
#템플릿 디렉토리가 있을 후보 디렉토리 리스트를 작성 장고 서버 초기 시작시에만 1회 작성됨





TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'askdjango','templates'),] #앱 아래 templates파일들은 APP_DIRS True로 줬기때문에
        #템플릿 리스트별로 다들어감 그러나 내가 만든 최상위 레이아웃은 프로젝트 앱 아래있는게 아니니 따로 지정해 줘야한다
        #템플릿이름들은 중복되면 안됨 리스트만들어서 위부터 찾아서 내려오므로 겹치면 다른 템플릿이 나올 수도 있음
        #그래서 앱/templates/앱/*.html 이런식으로 만들어주는거임 앱은 유일해야함
        ,
        'APP_DIRS': True,#이걸 True 로 주게되면 앱아래 templates 경로까지는 무조건 찾음
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'askdjango.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

INTERNAL_IPS = ['127.0.0.1'] #디버그툴바용

#디버그 툴바는 해당 템플릿에 <body>태그가 있어야만 주입이된다